image: Ubuntu

stack: jdk 11

build_script:
  - ./gradlew --console=plain --info build
  - ./gradlew --console=plain manifest --print
  - ./gradlew --console=plain dependencies --configuration=runtimeClasspath
